name: hoho_fashion

description: "hoho_fashion"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/image/
    - assets/image/character/
    - assets/image/character/eyes/
    - assets/image/character/hair/
    - assets/image/character/lips/
    - assets/image/character/dress/
    - assets/image/character/cloth-1/
    - assets/image/character/cloth-2/
    - assets/image/character/shoes/
    - assets/image/character/hairband/
    - assets/image/character/necklace/
    - assets/icon/category/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  icon_background_color: "#FFFFFF"
  image: "assets/icon/splash/splash_002.png"
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: "assets/icon/splash/splash_002.png"
